name: FastApi

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  create-virtualenv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pipenv
        run: pipx install pipenv
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          # cache: 'pipenv'
      - run: pipenv install --dev

  run-tests:
    needs: create-virtualenv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        env:
          AUTH_SECRET_KEY: ${{ secrets.AUTH_SECRET_KEY }}
      - run: pipenv run pytest -vv && bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}

  run-linters:
    needs: create-virtualenv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pipenv run isort . --diff --check-only
      - run: pipenv run black --check --diff .
