name: FastApi

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
      env:
        AUTH_SECRET_KEY: ${{ secrets.AUTH_SECRET_KEY }}
      - run: |
          pip install pipenv
          pipenv install --dev
          pytest --dist load -vv -n auto && bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
          isort . --diff --check-only
          black --check --diff .
